/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118321-g4c96d6bf75-20250118"
#endif /* AVUTIL_FFVERSION_H */
